[env:esp32-s3-devkitc-1]
; --- CORE 3.0 FIX (QUAN TRỌNG NHẤT) ---
; Dòng này giúp tải Arduino Core 3.0.x, chứa file periman.h và hỗ trợ GFX mới nhất
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip

board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- CẤU HÌNH BỘ NHỚ CHO MÀN AMOLED ---
; Bắt buộc phải là QIO và OPI PSRAM
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = huge_app.csv

; --- CỜ BIÊN DỊCH ---
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ; Bật Serial qua USB (để debug)
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ; Tắt các cảnh báo phiền phức
    -w

; --- THƯ VIỆN ---
lib_deps = 
    ; Thư viện quản lý nguồn
    lewisxhe/XPowersLib @ ^0.2.6
    
    ; Thư viện cảm biến
    lewisxhe/SensorLib @ ^0.2.0
    
    ; Thư viện màn hình (Lấy bản mới nhất để có driver CO5300)
    moononournation/GFX Library for Arduino @ ^1.5.0

